catalog/urls.py
from django.urls import path, include

from catalog import views

app_name = "catalog"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("dostavka/", views.dostavka, name="dostavka"),
    path("inform/", views.inform, name="inform"),
]

goods/urls.py
from django.urls import path

from goods import views


app_name = "goods"

urlpatterns = [
    path("search/", views.cataloge, name="search"),
    path("", views.cataloge, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product"),
]

localmagaz/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static


from localmagaz import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("cataloge/", include("goods.urls", namespace="cataloge")),
    path("user/", include("users.urls", namespace="user")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include

from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
]

goods/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL"
    )

    class Meta:
        db_table = "category"
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL"
    )
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(
        upload_to="goods_images", blank=True, null=True, verbose_name="Изображение"
    )
    price = models.DecimalField(
        default=0.00, max_digits=7, decimal_places=2, verbose_name="Цена"
    )
    discount = models.DecimalField(
        default=0.00, max_digits=4, decimal_places=2, verbose_name="Скидка в %"
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    category = models.ForeignKey(
        to=Categories, on_delete=models.CASCADE, verbose_name="Категория"
    )

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self):
        return f"{self.name} Количество - {self.quantity}"

    def display_id(self):
        return f"{self.id:05}"

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)

        return self.price

users/models.py
from django.db import models

# Create your models here.

catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse

from goods.models import Categories


def index(request):

    context: dict = {
        "title": "Baby Land - Главная",
        "content": "Магазин детских игрушек BABY LAND",
    }

    return render(request, "catalog/index.html", context)


def about(request):
    context: dict = {
        "title": "Baby Land - О нас",
        "content": "О нас",
        "text_on_page": "Мы работаем и радуем вас уже более 5 лет. Все товары сертифицированы. Мы уважаем и ценим каждого нашего клиента. У нас есть приятные бонусы нашим постоянным клиентам!",
    }

    return render(request, "catalog/about.html", context)


def dostavka(request):
    context: dict = {
        "title": "Baby Land - Доставка и оплата",
        "content": "Доставка и оплата",
        "text_on_page": "Вы можете забрать ваш заказ бесплатно в удобное для вас время в нашем магазине (с 09.00 до 20.00 пн-вс). Осуществляется доставка по городу (стоимость доставки зависит от района)",
    }

    return render(request, "catalog/dostavka.html", context)


def inform(request):
    context: dict = {
        "title": "Baby Land - Контактная информация",
        "content": "Контактная информация",
        "text_on_page": "Адрес магазина: г.Гродно, ул.Суворова, 127А. Телефон: (029)200-01-07",
    }

    return render(request, "catalog/inform.html", context)

goods/views.py
from unicodedata import category
from django.core.paginator import Paginator
from django.shortcuts import render

from goods.models import Products
from goods.utils import q_search


def cataloge(request):

    query = request.GET.get("q", None)

    goods = Products.objects.all()

    context = {
        "title": "Baby Land - Каталог",
        "goods": goods,
    }
    return render(request, "goods/cataloge.html", context)


def product(request, product_slug):

    product = Products.objects.get(slug=product_slug)

    context = {"product": product}

    return render(request, "goods/product.html", context=context)

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render


def login(request):

    context = {"title": "Home - Авторизация"}
    return render(request, "users/login.html", context)


def registration(request):

    context = {"title": "Home - Регистрация"}
    return render(request, "users/registration.html", context)


def profile(request):

    context = {
        "title": "Home - Кабинет",
    }
    return render(request, "users/profile.html", context)


def logout(request): ...

catalog/templates/catalog/about.html
{% extends "catalog/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock css %}


{% block content %}
	<div class="mt-5 pt-5 bg-white custom-shadow rounded">
		<h2 class="m-2"><strong>{{ content }}</strong></h2>
		<p class="m-2">{{ text_on_page }}</p>
	</div>
{% endblock content %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; BABY LAND 2024</p>
    </div>
</footer>
{% endblock footer %}

catalog/templates/catalog/base.html
{% load static %}
{% load goods_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}
	{% endblock css %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "catalog:index" %}">Baby Land</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="{% url "catalog:dostavka" %}">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "catalog:inform" %}">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "catalog:about" %}">О нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url "users:login" %}">Войти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url "users:profile" %}">Личный кабинет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="{% url "users:logout" %}">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search" action="{% url "cataloge:search" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16" height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{% url "cataloge:index" %}">{{ category.name }}</a></li>
                        {% endfor %}

                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24" height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button"
                                                                    class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button"
                                                                    class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 р</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static "deps/icons/trash3-fill.svg" %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 р</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div>
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </section>

	{% block footer %}{% endblock footer %}

    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>

</html>

catalog/templates/catalog/dostavka.html
{% extends "catalog/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock css %}


{% block content %}
	<div class="mt-5 pt-5 bg-white custom-shadow rounded">
		<h2 class="m-2"><strong>{{ content }}</strong></h2>
		<p class="m-2">{{ text_on_page }}</p>
	</div>
{% endblock content %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; BABY LAND 2024</p>
    </div>
</footer>
{% endblock footer %}

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock css %}


{% block content %}
    <h1 class="mt-5 pt-5 mx-5 p-5 px-4"><strong>{{ content }}</strong></h1>
{% endblock content %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; BABY LAND 2024</p>
    </div>
</footer>
{% endblock footer %}

catalog/templates/catalog/inform.html
{% extends "catalog/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock css %}


{% block content %}
	<div class="mt-5 pt-5 bg-white custom-shadow rounded">
		<h2 class="m-2"><strong>{{ content }}</strong></h2>
		<p class="m-2">{{ text_on_page }}</p>
	</div>
{% endblock content %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; BABY LAND 2024</p>
    </div>
</footer>
{% endblock footer %}

goods/templates/goods/cataloge.html
{% extends "catalog/base.html" %}
{% load static %}


{% block content %}
<div class="row">
	<!-- Форма фильтров -->
	<div class="dropdown mb-2">
		<button class="btn btn-secondary dropdown-toggle btn-dark" type="button"
			data-bs-toggle="dropdown" aria-expanded="false">
			Фильтры
		</button>

		<form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
			<div class="form-check text-white mx-3">
				<input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault"
					value="on">
				<input type="hidden" name="q" value="request.GET.q">
				<label class="form-check-label" for="flexCheckDefault">
					Товары по акции
				</label>
			</div>
			<p class="text-white mx-3 mt-3">Сортировать:</p>
			<div class="form-check text-white mx-3">
				<input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1"
					value="default" checked>
				<label class="form-check-label" for="flexRadioDefault1">
					По умолчанию
				</label>
			</div>
			<div class="form-check text-white mx-3">
				<input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2"
					value="price">
				<label class="form-check-label" for="flexRadioDefault2">
					От дешевых к дорогим
				</label>
			</div>
			<div class="form-check text-white mx-3">
				<input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3"
					value="-price">
				<label class="form-check-label" for="flexRadioDefault3">
					От дорогих к дешевым
				</label>
			</div>
			<button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
		</form>
	</div>




	{% for product in goods %}
	<!-- Карта товара -->
	<div class="col-lg-4 col-md-6 p-4">
		<div class="card border-primary rounded custom-shadow">
			{% if product.image %}
				<img src="{{ product.image.url }}" class="card-img-top" alt="product.name">
			{% else %}
				<img src="{% static "deps/images/Not found image.png" %}}" class="card-img-top" alt="...">
			{% endif %}
			<div class="card-body">
				<a href="{% url "cataloge:product" product.slug %}">
					<p class="card-title">{{ product.name }}</p>
				</a>
				<p class="card-text">{{ product.description|truncatechars:54 }}</p>
				<p class="product_id">id: {{ product.display_id }}</p>
				<div class="d-flex justify-content-between">

					{% if product.discount %}
						<p><s>{{ product.price }}</s> р</p>
						<p><strong>{{ product.sell_price }} р</strong></p>
						<span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
					{% else %}
						<p><strong>{{ product.price }} р</strong></p> 
					{% endif %}
					
					<a href="#" class="btn add-to-cart">
						<img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
							width="32" height="32">
					</a>
				</div>
			</div>
		</div>
	</div>
	{% endfor %}
	



</div>
<!-- Пагинация -->
<nav aria-label="Page navigation example">
	<ul class="pagination justify-content-center my-4">
		<div class="custom-shadow d-flex">
			<li class="page-item disabled">
				<a class="page-link">Назад</a>
			</li>
			<li class="page-item"><a class="page-link" href="#">1</a></li>
			<li class="page-item"><a class="page-link" href="#">2</a></li>
			<li class="page-item"><a class="page-link" href="#">3</a></li>
			<li class="page-item">
				<a class="page-link" href="#">Вперед</a>
			</li>
		</div>
	</ul>
</nav>
{% endblock  %}



{% block footer %}
<footer class="py-4 bg-dark">
	<div class="container">
		<p class="m-0 text-center text-white">Copyright &copy; BABY LAND 2024</p>
	</div>
</footer>
{% endblock  %}

goods/templates/goods/product.html
{% extends "catalog/base.html" %}
{% load static %}


{% block content %}
<div class="container mt-5">
	<div class="card mb-4 custom-shadow">
		<div class="row">
			<!-- Миниатюры -->
			<div class="col-md-4">
				<img src="{{ product.image.url }}"
					class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
			</div>
			<div class="col-md-4 ">
				<p class="product_id mt-3">id: {{ product.display_id }}</p>
			</div>
			<!-- Увеличить изображение в модальном окне -->
			<div class="modal fade" id="imageModal1" tabindex="-1"
				aria-labelledby="imageModal1Label" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="imageModal1Label">Изображение 1</h5>
							<button type="button" class="btn-close" data-bs-dismiss="modal"
								aria-label="Закрыть"></button>
						</div>
						<div class="modal-body">
							<img src="{{ product.image.url }}" class="img-fluid" alt="Изображение 1">
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Описание товара -->
		<div class="card-body">
			<p class="card-text">Цена: <strong>{{ product.sell_price }} р</strong></p>
			<h5 class="card-title">{{ product.name }}</h5>
			<p class="card-text">{{ product.description }}</p>
			<a href="#" class="btn btn-dark add-to-cart">Добавить в корзину</a>
		</div>
	</div>
</div>
{% endblock  %}

users/templates/users/login.html
{% extends "catalog/base.html" %}
{% load static %}


{% block content %}
<div class="row">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
				<h2 class="text-center mb-4">Авторизация</h2>
				<form>
					<div class="mb-3">
						<label for="username" class="form-label">Имя пользователя</label>
						<input type="text" class="form-control" id="username" placeholder="Введите ваше имя пользователя" required>
					</div>
					<div class="mb-3">
						<label for="password" class="form-label">Пароль</label>
						<input type="password" class="form-control" id="password" placeholder="Введите ваш пароль" required>
					</div>
					<button type="submit" class="btn btn-dark btn-block">Войти</button>
				</form>
				<div class="mt-3">
					<a href="#">Забыли пароль?</a> | <a href="{% url "users:registration" %}">Создать аккаунт</a>
				</div>
				<hr>
				<div class="text-center">
					<p>Или авторизуйтесь через:</p>
					<a href="#" class="btn btn-dark">
						<img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
						Google
					</a>
					<a href="#" class="btn btn-dark">
						<img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
						Facebook
					</a>
					<a href="#" class="btn btn-dark">
						<img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
						GitHub
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock  %}

users/templates/users/profile.html
{% extends "catalog/base.html" %}
{% load static %}

{% block content %}
<div class="row">
	<div class="container mt-5">
		<div class="row">
			<!-- Профиль с данными пользователя -->
			<div class="col-md-5">
				<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
					<h3 class="text-center mb-4">Профиль пользователя</h3>
					<form>
						<div class="row">
							<div class="col-md-12 mb-3 text-center">
								<img src="{% static "deps/images/baseavatar.jpg" %}"
									alt="Аватар пользователя" class="img-fluid rounded-circle"
									style="max-width: 150px;">
								<input type="file" class="form-control mt-3" id="avatar"
									accept="image/*">
							</div>
							<div class="col-md-12 mb-3">
								<label for="firstName" class="form-label">Имя*</label>
								<input type="text" class="form-control" id="firstName"
									placeholder="Введите ваше имя" value="" required>
							</div>
							<div class="col-md-12 mb-3">
								<label for="lastName" class="form-label">Фамилия*</label>
								<input type="text" class="form-control" id="lastName"
									placeholder="Введите вашу фамилию" value="" required>
							</div>
							<div class="col-md-12 mb-3">
								<label for="username" class="form-label">Имя пользователя*</label>
								<input type="text" class="form-control" id="username"
									placeholder="Введите ваше имя пользователя" value="" required>
							</div>
							<div class="col-md-12 mb-3">
								<label for="email" class="form-label">Email*</label>
								<input type="email" class="form-control" id="email"
									placeholder="Введите ваш email *youremail@example.com" value=""
									required>
							</div>
						</div>
						<button type="submit" class="btn btn-dark">Сохранить</button>
					</form>
				</div>
			</div>
			<!-- Корзина -->
			<div class="col-md-7">
				<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
					<h3 class="text-center mb-4">Корзина</h3>
					<div class="container" id="cart-items-container">
						<!-- Разметка корзины -->
						<!-- Закончилась разметка корзины -->
					</div>
					<a class="btn btn-dark" href="../orders/create_order.html">
						Оформить заказ
					</a>
				</div>
			</div>
			<!-- Оформленные заказы -->
			<div class="col-md-12">
				<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
					<h3 class="text-center mb-4">Мои заказы</h3>
					<!-- Разметка заказов -->
					<div class="container">
						<div class="accordion" id="accordionExample">
							<div class="accordion-item">
								<h2 class="accordion-header" id="heading1">
									<button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
										Заказ № 274 - 14 мая 2024 10:04 | Статус:<strong class="mx-2"> Получен</strong>
									</button>
								</h2>
								<div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
									<div class="accordion-body">
										<table class="table table-dark table-hover">
											<thead>
												<tr>
													<th>Товар</th>
													<th>Количество</th>
													<th>Цена</th>
													<th>Общая стоимость</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td><a class="text-white" href="#">Конструктор LEGO Гараж</a></td>
													<td>1</td>
													<td>154.80 р</td>
													<td>154.80 р</td>
													
												</tr>
											</tbody>
										</table>

									</div>
								</div>
							</div>
							<div class="accordion-item">
								<h2 class="accordion-header" id="heading2">
									<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
										Заказ № 275 - 20 мая 2024 11:27 | Статус: <strong> В обработке</strong>
									</button>
								</h2>
								<div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
									<div class="accordion-body">
										<table class="table table-dark table-hover">
											<thead>
												<tr>
													<th>Товар</th>
													<th>Количество</th>
													<th>Цена</th>
													<th>Общая стоимость</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td><a class="text-white" href="#">Кукла Barbie Mattel Спальня</a></td>
													<td>2</td>
													<td>101.65 р</td>
													<td>101.65 р</td>
													
												</tr>
											</tbody>
										</table>

										<div class="d-flex justify-content-between">
											<p><strong>Итого:</strong></p>
											<p><strong>101.65 р</strong></p>

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Закончилась разметка заказов -->
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock  %}